// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: '',
    appId: '1:774376187889:web:303d4da5ac1a92f6d40650',
    messagingSenderId: '774376187889',
    projectId: '',
    authDomain: 'helphub-99b15.firebaseapp.com',
    storageBucket: 'helphub-99b15.firebasestorage.app',
    measurementId: 'G-V7SXD1ZF1C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: '',
    appId: '1:774376187889:android:9a50ae51c1bcc0f2d40650',
    messagingSenderId: '774376187889',
    projectId: '',
    storageBucket: 'helphub-99b15.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: '',
    appId: '1:774376187889:ios:7965d6cf90192443d40650',
    messagingSenderId: '774376187889',
    projectId: '',
    storageBucket: 'helphub-99b15.firebasestorage.app',
    iosBundleId: 'com.OurCodingCafe.helpHub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: '',
    appId: '1:774376187889:ios:7965d6cf90192443d40650',
    messagingSenderId: '774376187889',
    projectId: '',
    storageBucket: 'helphub-99b15.firebasestorage.app',
    iosBundleId: 'com.OurCodingCafe.helpHub',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: '',
    appId: '1:774376187889:web:9c5742d72d32228fd40650',
    messagingSenderId: '774376187889',
    projectId: '',
    authDomain: 'helphub-99b15.firebaseapp.com',
    storageBucket: 'helphub-99b15.firebasestorage.app',
    measurementId: 'G-PEKLY89P5C',
  );
}
